name: number_slider
description: A number slider to choose a integer value
version: 0.0.1
homepage: steinel-it.de

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  infinite_listview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
